integration:
  datawarehousereader:
    connectTimeout: 10
    readTimeout: 20
  invoicecache:
    connectTimeout: 10
    readTimeout: 20
  idata:
    connectTimeout: 10
    readTimeout: 20
logbook:
  body-filters:
    json-path:
      - key: "['file','content']"
        value: '[base64]'

logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
resilience4j:
  circuitbreaker:
    instances:
      datawarehousereader:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
      invoicecache:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
spring:
  application:
    name: api-invoices
  security:
    oauth2:
      client:
        registration:
          datawarehousereader:
            authorization-grant-type: client_credentials
            provider: datawarehousereader
          invoicecache:
            authorization-grant-type: client_credentials
            provider: invoicecache
springdoc:
  swagger-ui:
    operationsSorter: method
